# Generated by Django 5.2.10 on 2026-01-14 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_contratacion',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('baja', 'Baja')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default=5939999999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='unidad_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
